# JWT
jwt.secret=mySuperSecretKeyThatIsAtLeast256BitsLongForHS512Algorithm12345
jwt.expiration=86400000

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/gurukul_db
spring.datasource.username=avishek
spring.datasource.password=Avishek123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
server.servlet.context-path=/api